apiVersion: v1
kind: Service
metadata:
  name: sudoku-svc
  namespace: sudoku
spec:
  selector:
    app: sudoku
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer   # use NodePort for local/minikube
